modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "accessible-step"
version = "${version}"
displayName = "Accessible Step"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.accessible-step]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)" # UPDATE_NEOFORGE
ordering = "NONE"
side = "CLIENT"

[[dependencies.accessible-step]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)" # UPDATE_MINECRAFT
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "accessible-step.mixins.json"

[mc-publish]
modrinth = "z6d6n7ve"
curseforge = 1044724