name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Gradle
        uses: SecretOnline/minecraft-actions/setup-mod-gradle@v2

      - name: Build
        run: ./gradlew clean build

      - name: Upload fabric artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-fabric
          path: fabric/build/libs/

      - name: Upload neoforge artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-neoforge
          path: neoforge/build/libs/

  gametest:
    name: Run game tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends imagemagick xvfb x11-apps

          export DISPLAY=:1
          echo "DISPLAY=:1" >> "$GITHUB_ENV"

          # Minecraft opens to 854x480 by default. No point in having a larger frame buffer.
          sudo Xvfb -ac :1 -screen 0 854x480x24 > /dev/null 2>&1 &
          sleep 1

      - name: Setup Gradle
        uses: SecretOnline/minecraft-actions/setup-mod-gradle@v2

      - name: Run gametests
        run: ./gradlew runClientGameTest --args="-Dfabric.client.gametest.disableNetworkSynchronizer=true"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: client-gametest-screenshots
          path: fabric/build/run/clientGameTest/screenshots/

  get-live-test-matrix:
    name: Get test matrix
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{ steps.get-test-versions.outputs.test-matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Get versions
        id: get-test-versions
        uses: SecretOnline/minecraft-actions/get-test-matrix@v2

  live-test:
    name: Test (${{ matrix.versions.minecraft-version }})
    runs-on: ubuntu-latest
    needs:
      - build
      - get-live-test-matrix
    strategy:
      matrix:
        versions: ${{ fromJson(needs.get-live-test-matrix.outputs.test-matrix) }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Setup Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends imagemagick xvfb x11-apps

          export DISPLAY=:1
          echo "DISPLAY=:1" >> "$GITHUB_ENV"

          # Minecraft opens to 854x480 by default. No point in having a larger frame buffer.
          sudo Xvfb -ac :1 -screen 0 854x480x24 > /dev/null 2>&1 &
          sleep 1

      - name: Setup Java ${{ matrix.versions.java-version }}
        id: setup-java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.versions.java-version }}
          distribution: zulu

      - name: Setup server
        uses: SecretOnline/minecraft-actions/setup-mc-server@v2
        with:
          server-directory: server
          minecraft-version: ${{ matrix.versions.minecraft-version }}
          loader: fabric
          accept-eula: true

      - name: Setup client
        uses: SecretOnline/minecraft-actions/setup-mc-client@v2
        with:
          client-directory: client
          minecraft-version: ${{ matrix.versions.minecraft-version }}
          loader: fabric

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: build-fabric

      - name: Install mods
        run: |
          fabric_api_url=$(curl -sg -A "secret_online/accessible-step (mc@secretonline.co)" "https://api.modrinth.com/v2/project/P7dR8mSH/version" | jq -r "[.[] | select(.game_versions[] == \"${{ matrix.versions.minecraft-version }}\")][0].files[0].url")

          mkdir -p server/mods
          mkdir -p client/mods

          wget -q -O server/mods/fabric-api.jar "$fabric_api_url"
          cp server/mods/fabric-api.jar client/mods/fabric-api.jar

          mod_file=$(ls -1 | grep ".jar" | grep -Ev "\-(sources|shadow).jar" | grep -v "\-dev")
          mv $mod_file server/mods/

      - name: Run server
        uses: SecretOnline/minecraft-actions/run-mc-server@v2
        with:
          server-directory: server
          log-file: server/server.log

      - name: Run client
        uses: SecretOnline/minecraft-actions/run-mc-client@v2
        with:
          client-directory: client
          log-file: client/client.log
          width: 854
          height: 480
          server-address: localhost:25565

      - name: Take screenshot
        working-directory: client
        run: |
          xwd -display $DISPLAY -root -silent | convert xwd:- png:./screenshot.png

      - name: Prepare artifact files
        run: |
          if [ -f client/client.log ]; then
            cp client/client.log client.log
          fi
          if [ -f client/screenshot.png ]; then
            cp client/screenshot.png screenshot.png
          fi
          if [ -f server/server.log ]; then
            cp server/server.log server.log
          fi

      - name: Upload test artifacts
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: test-result-${{ matrix.versions.minecraft-version }}
          path: |
            server.log
            client.log
            screenshot.png
          retention-days: 7

      - name: Upload screenshot to Imgur
        id: upload-screenshot
        run: |
          response=$(curl -X POST -s -F "image=@screenshot.png" -H "Authorization: Client-ID ${{ secrets.IMGUR_CLIENT_ID }}" https://api.imgur.com/3/image)
          echo $response

          url=$(echo $response | jq -r .data.link)

          echo "url=$url" >> "$GITHUB_OUTPUT"

      - name: Add job summary
        run: |
          cat << "EOF_AiVMO7YIg1" >> job-summary.md
          ## Test screenshot (${{ matrix.versions.minecraft-version }})

          ![Screenshot](${{ steps.upload-screenshot.outputs.url }})

          EOF_AiVMO7YIg1

          cat job-summary.md >> $GITHUB_STEP_SUMMARY

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v3
        if: github.event_name == 'pull_request'
        with:
          message-id: "mod-test-${{ matrix.versions.minecraft-version }}"
          message-path: job-summary.md
